name: Push to docker hub

on:
  release:
      types: [published]
  workflow_dispatch:
    
jobs:
  deploy:
    if: ${{ github.repository == 'screamz2k/PhoenixC2' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: screamz2k
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: screamz2k/phoenixc2:latest
